export const getStyles = (theme) => ({
  dashboard: {
    display: "flex",
    height: "100vh",
    overflow: "hidden",
    backgroundColor: theme.palette.background.default,
    fontFamily: theme.typography.fontFamily,
    color: theme.palette.text.primary,
  },
  sidebar: {
    width: "245px",
    minWidth: "245px",
    height: "100vh",
    position: "fixed",
    top: 0,
    left: 0,
    bottom: 0,
    zIndex: 1000,
    backgroundColor: theme.palette.background.paper,
    borderRight: `${theme.border.width} ${theme.border.style} ${theme.palette.border.light}`,
    display: "flex",
    flexDirection: "column",
    boxSizing: "border-box",
    overflowY: "auto",
  },
  profile: {
    display: "flex",
    alignItems: "center",
    gap: "14px",
    padding: "20px 18px",
    borderBottom: `${theme.border.width} ${theme.border.style} ${theme.palette.border.light}`,
  },
  avatar: {
    width: "48px",
    height: "48px",
    borderRadius: theme.shape.boxRadius,
    backgroundColor: theme.palette.primary.main,
    color: theme.palette.text.white,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontWeight: 700,
    fontSize: "18px",
    flexShrink: 0,
  },
  userName: {
    margin: "0 0 4px",
    fontSize: "16px",
    fontWeight: 700,
    color: theme.palette.text.primary,
  },
  userEmail: {
    margin: 0,
    fontSize: "12px",
    color: theme.palette.text.primary,
  },
  menu: {
    padding: `${theme.spacing.lg} ${theme.spacing.md} ${theme.spacing.sm} ${theme.spacing.md}`,
  },
  menuTitle: {
    margin: "0 0 12px 6px",
    fontSize: "11px",
    color: theme.palette.text.primary,
    letterSpacing: "1px",
    fontWeight: 800,
  },
  navLink: {
    display: "block",
    padding: "11px 14px",
    marginBottom: "5px",
    borderRadius: "7px",
    textDecoration: "none",
    color: theme.palette.text.primary,
    fontSize: "14px",
    fontWeight: 500,
    cursor: "pointer",
    border: "1px solid transparent",
    borderLeft: "4px solid transparent",
  },
  activeLink: {
    display: "block",
    padding: "11px 14px",
    marginBottom: "5px",
    borderRadius: "7px",
    textDecoration: "none",
    color: theme.palette.text.primary,
    backgroundColor: theme.palette.background.paper,
    border: `1px solid ${theme.palette.secondary.main}`,
    borderLeft: `4px solid ${theme.palette.secondary.main}`,
    fontSize: "14px",
    fontWeight: 600,
    cursor: "pointer",
  },
  accountLink: {
    display: "block",
    padding: "11px 14px",
    textDecoration: "none",
    color: theme.palette.text.primary,
    fontSize: "14px",
    fontWeight: 800,
},
  bottomMenu: {
    marginTop: "20px",
    padding: "15px 14px 20px",
  },
  quickActionMenu: {
    marginTop: "auto",
    padding: "15px 14px 20px"
  },
  signOut: {
    display: "block",
    padding: "11px 14px",
    textDecoration: "none",
    color: theme.palette.text.primary,
    fontSize: "14px",
    cursor: "pointer",
  },
  main: {
    flex: 1,
    marginLeft: "245px",
    minWidth: 0,
    display: "flex",
    flexDirection: "column",
    height: "100vh",
    overflow: "hidden",
    backgroundColor: theme.palette.background.default,
  },
  topbar: {
    position: "fixed",
    width: "100%",
    height: "70px",
    minHeight: "70px",
    flexShrink: 0,
    backgroundColor: theme.palette.primary.main,
    color: theme.palette.text.white,
    display: "flex",
    alignItems: "center",
    padding: "0 30px",
    boxSizing: "border-box",
  },
  topbarTitle: {
    margin: 0,
    fontSize: "24px",
    fontWeight: 700,
  },
  
  content: {
    flex: 1,
    padding: "30px 32px",
    marginTop: "20px",
    overflowY: "auto",
    boxSizing: "border-box",
    maxWidth: "1100px",
    width: "100%",
  },
  welcomeBox: {
    marginTop: "40px",
    backgroundColor: theme.palette.background.paper,
    border: `1px solid ${theme.palette.secondary.main}`,
    borderTop: `4px solid ${theme.palette.secondary.main}`,
    borderRadius: "16px",
    padding: "36px",
    boxShadow: "none",
    boxSizing: "border-box",
  },
  welcomeTitle: {
    margin: "0 0 8px",
    fontSize: "28px",
    fontWeight: 700,
    color: theme.palette.text.primary,
  },
  description: {
    margin: "0 0 30px",
    fontSize: "14px",
    lineHeight: "1.6",
    color: theme.palette.text.primary,
  },
  cards: {
    display: "grid",
    gridTemplateColumns: "repeat(4, 1fr)",
    gap: "24px",
    marginBottom: "32px",
  },
  card: {
    padding: "22px",
    minHeight: "140px",
    border: `1px solid ${theme.palette.secondary.main}`,
    borderRadius: "12px",
    backgroundColor: theme.palette.background.paper,
    boxSizing: "border-box",
    display: "flex",
    flexDirection: "column",
  },
  cardTitle: {
    margin: "0 0 10px",
    fontSize: "16px",
    fontWeight: 700,
    color: theme.palette.text.primary,
  },
  cardText: {
    margin: 0,
    fontSize: "13px",
    lineHeight: "1.5",
    color: theme.palette.text.primary,
    flex: 1,
  },
  cardLine: {
    width: "75%",
    height: "4px",
    marginTop: "auto",
    paddingTop: "0",
    borderRadius: "5px",
    backgroundColor: theme.palette.primary.main,
  },
  quickTitle: {
    margin: "30px 0 16px",
    fontSize: "20px",
    fontWeight: 700,
    color: theme.palette.text.primary,
  },
  actions: {
    display: "grid",
    gridTemplateColumns: "repeat(2, 1fr)",
    gap: "24px",
  },
  actionCard: {
    display: "block",
    padding: "24px",
    minHeight: "100px",
    border: `1px solid ${theme.palette.secondary.main}`,
    borderRadius: "12px",
    backgroundColor: theme.palette.background.paper,
    textDecoration: "none",
    boxSizing: "border-box",
  },
  actionTitle: {
    margin: "0 0 6px",
    fontSize: "16px",
    fontWeight: 700,
    color: theme.palette.text.primary,
  },
  actionText: {
    margin: 0,
    fontSize: "13px",
    color: theme.palette.text.primary,
  },
  
});
