export const getStyles = (theme) => ({
  dashboard: {
    display: "flex",
    minHeight: "100vh",
    backgroundColor: theme.palette.background.default,
    fontFamily: theme.typography.fontFamily,
    color: theme.palette.text.primary,
  },
  sidebar: {
    width: "245px",
    minWidth: "245px",
    backgroundColor: theme.palette.background.paper,
    borderRight: `${theme.border.width} ${theme.border.style} ${theme.palette.border.light}`,
    display: "flex",
    flexDirection: "column",
    boxSizing: "border-box",
  },
  profile: {
    display: "flex",
    alignItems: "center",
    gap: "14px",
    padding: "20px 18px",
    borderBottom: `${theme.border.width} ${theme.border.style} ${theme.palette.border.light}`,
  },
  avatar: {
    width: "48px",
    height: "48px",
    borderRadius: theme.shape.boxRadius,
    backgroundColor: theme.palette.primary.main,
    color: theme.palette.text.white,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontWeight: 700,
    fontSize: "18px",
    flexShrink: 0,
  },
  userName: {
    margin: "0 0 4px",
    fontSize: "16px",
    fontWeight: 700,
    color: theme.palette.text.primary,
  },
  userEmail: {
    margin: 0,
    fontSize: "12px",
    color: theme.palette.text.secondary,
  },
  menu: {
    padding: "28px 14px",
  },
  menuTitle: {
    margin: "0 0 12px 6px",
    fontSize: "11px",
    color: theme.palette.text.secondary,
    letterSpacing: "1px",
    fontWeight: 600,
  },
  navLink: {
    display: "block",
    padding: "11px 14px",
    marginBottom: "5px",
    borderRadius: "7px",
    textDecoration: "none",
    color: theme.palette.text.secondary,
    fontSize: "14px",
    fontWeight: 500,
    cursor: "pointer",
  },
  activeLink: {
    display: "block",
    padding: "11px 14px",
    marginBottom: "5px",
    borderRadius: "7px",
    textDecoration: "none",
    color: theme.palette.primary.main,
    backgroundColor: theme.palette.background.paper,
    border: `1px solid ${theme.palette.secondary.main}`,
    borderLeft: `4px solid ${theme.palette.secondary.main}`,
    fontSize: "14px",
    fontWeight: 600,
    cursor: "pointer",
  },
  bottomMenu: {
    marginTop: "auto",
    padding: "15px 14px 20px",
  },
  signOut: {
    display: "block",
    padding: "11px 14px",
    textDecoration: "none",
    color: theme.palette.text.secondary,
    fontSize: "14px",
    cursor: "pointer",
  },
  main: {
    flex: 1,
    minWidth: 0,
    display: "flex",
    flexDirection: "column",
    backgroundColor: theme.palette.background.default,
  },
  topbar: {
    height: "70px",
    backgroundColor: theme.palette.primary.main,
    color: theme.palette.text.white,
    display: "flex",
    alignItems: "center",
    padding: "0 30px",
    boxSizing: "border-box",
  },
  topbarTitle: {
    margin: 0,
    fontSize: "24px",
    fontWeight: 700,
  },

  content: {
    flex: 1,
    padding: "40px 48px", 
    overflowY: "auto",
    boxSizing: "border-box",
    maxWidth: "1600px", 
    width: "100%",
  },
  welcomeBox: {
    backgroundColor: theme.palette.background.paper,
    border: `1px solid ${theme.palette.secondary.main}`,
    borderTop: `4px solid ${theme.palette.secondary.main}`,
    borderRadius: "16px", 
    padding: "36px",
    boxShadow: "none",
    boxSizing: "border-box",
  },
  welcomeTitle: {
    margin: "0 0 8px",
    fontSize: "28px", 
    fontWeight: 700,
  },
  description: {
    margin: "0 0 30px",
    fontSize: "14px", 
    lineHeight: "1.6",
    color: theme.palette.text.secondary,
  },
  cards: {
    display: "grid",
    gridTemplateColumns: "repeat(4, 1fr)",
    gap: "24px", 
    marginBottom: "32px",
  },
  card: {
    padding: "22px",
    minHeight: "140px", 
    border: `1px solid ${theme.palette.secondary.main}`,
    borderRadius: "12px", 
    backgroundColor: theme.palette.background.paper,
    boxSizing: "border-box",
    display: "flex",
    flexDirection: "column", 
  },
  cardTitle: {
    margin: "0 0 10px",
    fontSize: "16px",
    fontWeight: 700,
  },
  cardText: {
    margin: 0,
    fontSize: "13px",
    lineHeight: "1.5",
    color: theme.palette.text.secondary,
    flex: 1, 
  },
 
  cardLine: {
    width: "75%",
    height: "4px",
    marginTop: "auto", 
    paddingTop: "0",
    borderRadius: "5px",
    backgroundColor: theme.palette.primary.main,
  },
  quickTitle: {
    margin: "30px 0 16px",
    fontSize: "20px", 
    fontWeight: 700,
    color: theme.palette.text.primary,
  },
  actions: {
    display: "grid",
    gridTemplateColumns: "repeat(2, 1fr)",
    gap: "24px",
  },
  actionCard: {
    display: "block",
    padding: "24px", 
    minHeight: "100px", 
    border: `1px solid ${theme.palette.secondary.main}`,
    borderRadius: "12px",
    backgroundColor: theme.palette.background.paper,
    textDecoration: "none",
    boxSizing: "border-box",
  },
  actionTitle: {
    margin: "0 0 6px",
    fontSize: "16px",
    fontWeight: 700,
    color: theme.palette.primary.main,
  },
  actionText: {
    margin: 0,
    fontSize: "13px",
    color: theme.palette.text.secondary,
  },
});