export const getStyles = (theme) => ({
  mainContent: {
    width: "100%",
    flex: 1,
    padding: theme.spacing.lg,
    backgroundColor: theme.palette.background.default, 
    boxSizing: "border-box",
    overflowY: "auto",
  },
  profileCard: {
    width: "100%",
    backgroundColor: theme.palette.background.paper,
    border: `1px solid ${theme.palette.secondary.main}`,
    borderTop: `4px solid ${theme.palette.secondary.main}`, 
    borderRadius: theme.shape.largeRadius,
    padding: theme.spacing.xxxl,
    boxSizing: "border-box",
    boxShadow: theme.shadow.card,
  },
  title: {
    fontSize: theme.typography.h2.fontSize,
    fontWeight: theme.typography.h2.fontWeight,
    color: theme.palette.text.primary, 
    margin: `0 0 ${theme.spacing.lg} 0`,
    fontFamily: theme.typography.fontFamily,
  },
  sectionTitle: {
    fontSize: theme.typography.h3.fontSize,
    fontWeight: theme.typography.h3.fontWeight,
    color: theme.palette.text.primary,
    margin: `${theme.spacing.xl} 0 ${theme.spacing.md} 0`,
    fontFamily: theme.typography.fontFamily,
  },
  formGrid: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: theme.gap.large,
  },
  formGroup: {
    display: "flex",
    flexDirection: "column",
    gap: theme.gap.small,
    marginBottom: theme.spacing.md,
  },
  label: {
    fontSize: theme.typography.body.fontSize,
    fontWeight: theme.typography.heading.fontWeight,
    color: theme.palette.text.primary, 
    fontFamily: theme.typography.fontFamily,
  },
  input: {
    width: "100%",
    padding: `${theme.spacing.sm} ${theme.spacing.md}`,
    borderRadius: theme.shape.borderRadius,
    border: `${theme.border.width} ${theme.border.style} ${theme.palette.border.default}`,
    backgroundColor: theme.palette.background.paper,
    color: theme.palette.text.primary, 
    fontSize: theme.typography.body.fontSize,
    fontFamily: theme.typography.fontFamily,
    boxSizing: "border-box",
    outline: "none",
  },
  textarea: {
    width: "100%",
    minHeight: "110px",
    padding: `${theme.spacing.sm} ${theme.spacing.md}`,
    borderRadius: theme.shape.borderRadius,
    border: `${theme.border.width} ${theme.border.style} ${theme.palette.border.default}`,
    backgroundColor: theme.palette.background.paper,
    color: theme.palette.text.primary, 
    fontSize: theme.typography.body.fontSize,
    fontFamily: theme.typography.fontFamily,
    boxSizing: "border-box",
    outline: "none",
    resize: "vertical",
  },
  actions: {
    display: "flex",
    justifyContent: "flex-end",
    gap: theme.gap.medium,
    marginTop: theme.spacing.xxxl,
  },
  cancelButton: {
    padding: "10px 20px",
    borderRadius: theme.shape.borderRadius,
    border: `${theme.border.width} ${theme.border.style} ${theme.palette.border.default}`,
    backgroundColor: theme.palette.background.paper,
    color: theme.palette.text.primary, 
    fontSize: theme.typography.button.fontSize,
    fontWeight: theme.typography.button.fontWeight,
    cursor: "pointer",
    fontFamily: theme.typography.fontFamily,
  },
  saveButton: {
    padding: "10px 20px",
    borderRadius: theme.shape.borderRadius,
    border: "none",
    backgroundColor: theme.palette.secondary.main,
    color: theme.palette.text.white, 
    fontSize: theme.typography.button.fontSize,
    fontWeight: theme.typography.button.fontWeight,
    cursor: "pointer",
    fontFamily: theme.typography.fontFamily,
  },
});