export const getStyles = (theme) => ({
  content: {
    flex: 1,
    padding: theme.spacing.xl,
    overflowY: "auto",
    boxSizing: "border-box",
    backgroundColor: theme.palette.background.default,
  },
  securityContainer: {
    width: "100%",
    maxWidth: "100%",
  },
  securityCard: {
    width: "100%",
    backgroundColor: theme.palette.background.paper,
    border: `${theme.border.width} ${theme.border.style} ${theme.palette.secondary.main}`,
    borderTop: `4px solid ${theme.palette.secondary.main}`,
    borderRadius: theme.border.radius.lg,
    padding: theme.spacing.card,
    boxShadow: theme.shadow.card,
  },
  securityDescription: {
    fontSize: theme.typography.small.fontSize,
    fontWeight: theme.typography.small.fontWeight,
    color: theme.palette.text.secondary,
    lineHeight: theme.typography.body.lineHeight,
    margin: 0,
  },
  informationTitle: {
    fontSize: theme.typography.h3.fontSize,
    fontWeight: theme.typography.h3.fontWeight,
    color: theme.palette.text.primary,
    margin: 0,
    marginBottom: theme.spacing.sm,
  },
  formRow: {
    display: "flex",
    flexDirection: "row",
    gap: theme.gap.large,
    marginBottom: theme.spacing.lg,
    width: "100%",
  },
  formGroup: {
    flex: 1,
    display: "flex",
    flexDirection: "column",
    gap: theme.gap.small,
  },
  label: {
    fontSize: theme.typography.small.fontSize,
    fontWeight: theme.typography.body.fontWeight,
    color: theme.palette.text.secondary,
  },
  input: {
    width: "100%",
    boxSizing: "border-box",
    padding: `${theme.spacing.sm} ${theme.spacing.md}`,
    fontSize: theme.typography.body1.fontSize,
    fontFamily: theme.typography.fontFamily,
    color: theme.palette.text.primary,
    backgroundColor: theme.palette.background.default,
    border: `${theme.border.width} ${theme.border.style} ${theme.palette.border.light}`,
    borderRadius: `${theme.shape.borderRadius}px`,
    outline: "none",
  },
  actions: {
    display: "flex",
    flexDirection: "row",
    gap: theme.gap.medium,
    marginTop: theme.spacing.md,
  },
  clearButton: {
    padding: `${theme.spacing.xs} ${theme.spacing.lg}`,
    fontSize: theme.typography.button.fontSize,
    fontWeight: theme.typography.button.fontWeight,
    color: theme.palette.text.primary,
    backgroundColor: theme.palette.background.paper,
    border: `${theme.border.width} ${theme.border.style} ${theme.palette.border.default}`,
    borderRadius: theme.shape.pillRadius,
    cursor: "pointer",
  },
  updateButton: {
    padding: `${theme.spacing.xs} ${theme.spacing.lg}`,
    fontSize: theme.typography.button.fontSize,
    fontWeight: theme.typography.button.fontWeight,
    color: theme.palette.text.white,
    backgroundColor: theme.palette.secondary.main,
    border: `${theme.border.width} ${theme.border.style} ${theme.palette.secondary.main}`,
    borderRadius: theme.shape.pillRadius,
    cursor: "pointer",
  },
  informationTitle: {
    fontSize: theme.typography.h3.fontSize,
    fontWeight: theme.typography.h3.fontWeight,
    color: theme.palette.text.primary,
    margin: 0,
    marginBottom: theme.spacing.sm,
  },
  infoRow: {
    display: "grid",
    gridTemplateColumns: "repeat(3, 1fr)",
    gap: theme.gap.large,
    width: "100%",
  },
  infoCard: {
    display: "flex",
    flexDirection: "column",
    gap: theme.spacing.xs,
    backgroundColor: theme.palette.background.paper,
    border: `${theme.border.width} ${theme.border.style} ${theme.palette.border.light}`,
    borderRadius: theme.shape.largeRadius,
    padding: theme.spacing.md,
    boxShadow: theme.shadow.card,
  },
  infoIcon: {
    fontSize: theme.typography.h3.fontSize,
  },
  infoTitle: {
    fontSize: theme.typography.body.fontSize,
    fontWeight: 600,
    color: theme.palette.text.primary,
    margin: 0,
  },
  infoText: {
    fontSize: theme.typography.small.fontSize,
    color: theme.palette.text.secondary,
    margin: 0,
  },
});